### ISSUE TITLE
boost results by query locality

### ISSUE THREAD

**Issue by sevko** [pelias/api#91] opened 2015-04-06 15:26 UTC
A [query for `1710 Drew, Houston`](http://pelias.stage.mapzen.com/search?input=1710%20drew,%20Houston) currently ranks `1710 Drew Place, Claremont, CA` higher than `1710 Drew Street, Houston, TX`. According to @hkrishna , we only boost matches for `admin0`, `admin1`,  and `admin1_abbr`, meaning that the exact `locality` match doesn't get taken into account at all here. We should factor it into boosting if it doesn't significantly impact query times.

**Comment by hkrishna** [comment] 2015-04-09 17:26
Thanks @sevko for opening this issue. I will take a look at it soon. :smile_cat:

**Comment by hkrishna** [comment] 2015-04-16 20:13
So, pelias/api#102 implements this - however I see a few regressions. 

For example,

```new york, new york``` returns some point from NJ because it matches on ```locality``` and ```neighborhood``` with a value ```west new york``` :frowning:

@sevko do you wanna take this one over?

**Comment by sevko** [comment] 2015-04-16 20:25
Thanks for the DL @hkrishna. I'll check it out.

**Comment by sevko** [comment] 2015-04-27 15:18
After a lot of trial-and-error investigation in #102 , I've boiled down the necessary query logic to:

if an admin-value is present in the query
  * sort results by a `match` on `name.default`
  * sort results by a `match` on their admin values
    * only accept a match on **one** admin value, starting with admin0 and moving downwards (in other words, if a match on admin2 is found, **do not** go on to check **locality** and thus potentially compound the `_score`)
    * assign lower and lower `boost` values to lower admin values (so a record with a match on admin0 is ranked higher than one with a match on admin2)

**Comment by sevko** [comment] 2015-05-08 18:31
For the record, we've decided to table this until we have smarter address parsing in place (which can identify multiple admin values in a query string, like `Foo Bar, SoHo, New York`).

**Comment by missinglink** [comment] 2015-07-07 14:57
related? https://github.com/pelias/api/issues/148

**Comment by riordan** [comment] 2015-08-14 19:45
Hurray, we're working on this in #187.

Duplicate of other ticket.

**Closed** 2015-08-14 19:45 UTC
Labels: duplicate, enhancement, on-deck, v1
