### ISSUE TITLE
Feature for filtering results based on the city

### ISSUE THREAD

**Issue by ambodi** [pelias/api#711] opened 2016-10-27 11:19 UTC
Is it possible to limit results for /autocomplete or /search with a city? 

Our use-case:

We wanna get all available address numbers in a street within a specific city (makes sense right? since some names of the street are are duplicated at least in Sweden). 

We already know about bounding box option in /search but it does not look very optimal. 

Any feedback on this?

**Comment by orangejulius** [comment] 2016-10-27 14:23
Hey @ambodi,
What a coincidence, we were just talking about this exact feature the other day over in https://github.com/pelias/api/issues/373. It's something we believe we can implement without too much work, and it would be a big deal. I don't know exactly when, but we do hope to get to it sometime soon.

**Comment by ambodi** [comment] 2016-10-27 15:06
@orangejulius Hi! Awesome! 

This feature is kinda important for us to select Pelias. In case our help can make this feature to arrive faster, ping me 👍

**Comment by ambodi** [comment] 2016-10-31 10:45
@orangejulius can I help on this? since we need this feature to be available as soon as possible?

**Comment by orangejulius** [comment] 2016-11-01 20:23
Hey @ambodi,
Just to help us keep track of things, I'm closing this since it's an exact dupe of #373

**Closed by orangejulius** 2016-11-01 20:23 UTC
