### ISSUE TITLE
Should we add an Explain parameter for diagnosing system behavior?

### ISSUE THREAD

**Issue by riordan** [pelias/api#371] opened 2015-11-12 17:10 UTC
## The idea
We add to `/search`, `/autocomplete`, and `/reverse` a parameter called `explain` that runs and returns an Elasticsearch Explain for all subqueries to the search system so we can profile behaviors.

## Background
In thinking through some of the issues facing us on Autocomplete Balance behaviors (#328) and @orangejulius' work on the Autocomplete Tester (pelias/fuzzy-tester#23), it struck me that it might be particularly useful to understand why Elasticsearch is behaving the way it is from one `/autocomplete` query to the next.

We should  be able to understand why, for instance, when @randymeech searches for a strongly-matching address from Long Island (pelias/pelias#165) we get:
1. `190 dean` :white_check_mark: 
2. `190 dean s` :x: Sekgosese 1, NORTHERN PROVINCE, South Africa
3. `190 dean st` :white_check_mark: 
4. `190 dean str` :x: Sekgosese 1, NORTHERN PROVINCE, South Africa 

Having the ability to profile the scoring on this could provide us with a lot of insight.

As I recall, we talked about this briefly this past summer, but thought it might expose too much of the system internals (I think I raised that complaint and for that I recant).

Would love to have this and think it'd let us bring some more precision to our recalibrations.

Thoughts?

**Comment by dianashk** [comment] 2016-04-19 20:27
duplicate of pelias/pelias#207

**Closed by dianashk** 2016-04-19 20:27 UTC
Labels: discussion, feature, processed, question
