### ISSUE TITLE
Ensure results don't have duplicates

### ISSUE THREAD

**Issue by dianashk** [pelias/api#362] opened 2015-11-05 17:17 UTC
Results frequently have duplicate locations with the same or almost same properties. This is a result of having various data sources and consciously not deduping data among them. If a user searches for only OSM data, they should still see all the things OSM has for the given query. However, when no data source is specified, we should do our best to filter out things that look similar. We'll probably be able to select the prefered result based on source trust-factor:

1. WOF
2. OA
3. OSM

**Comment by riordan** [comment] 2015-11-11 22:00
Duplicate of pelias/api#339. Ironically.

**Closed** 2015-11-11 22:01 UTC
Labels: duplicate
