### ISSUE TITLE
`/search?categories` parameter accepts multiple categories

### ISSUE THREAD

**Issue by riordan** [pelias/api#175] opened 2015-07-28 21:03 UTC
Using the `categories` parameter to search, an API user may pass along several categories.

Multiple categories may be passed along, separated by a comma, or a comma separated by whitespace. Invalid categories are ignored (and a notification is passed along in the Error block of the response).

Categories are additive (OR's rather than ANDs) in that a query with multiple categories should not disqualify results that don't map to all categories.

**Comment by riordan** [comment] 2015-08-14 19:32
DUPE!

**Comment by orangejulius** [comment] 2015-08-20 21:10
More specifically, it's a dupe of #128

**Closed by orangejulius** 2015-08-20 21:10 UTC
Labels: 0 - Backlog, enhancement, in review, v1
