### ISSUE TITLE
Equivalent but non-equal street name values are causing duplicates

### ISSUE THREAD

**Issue by trescube** [pelias/api#588] opened 2016-07-15 21:27 UTC
We import OA and OSM records without normalization of the street fields, resulting in things like:

OA: `1090 North Charlotte Street`
OSM: `1090 N Charlotte Street`

Since our deduping logic compares street names without any normalization, both results are returned:
<img width="427" alt="screen shot 2016-07-15 at 5 19 50 pm" src="https://cloud.githubusercontent.com/assets/658991/16888818/678a4518-4ab0-11e6-93a6-49ba7b1e13b5.png">

One strategy we could explore is to compare the outputs of libpostals address expansion utility when fed with the street name fields.  

For instance, address expansion gets the following for `North Charlotte Street`:
- `north charlotte street`

It generates the following for `N Charlotte Street`:
- `n charlotte street`
- `north charlotte street`

It stands to reason that if `housenumber` and coarse `gid` fields match and the intersection of the sets of address expansions is non-empty, then the 2 `address` layer records are duplicates.

**Comment by orangejulius** [comment] 2018-07-17 02:45
This looks very similar to the following issues:

https://github.com/pelias/pelias/issues/688
https://github.com/pelias/pelias/issues/438

**Comment by orangejulius** [comment] 2019-02-14 04:44
Closing as a dupe of https://github.com/pelias/pelias/issues/438 since that one is in the pelias repo and more visible

**Closed by orangejulius** 2019-02-14 04:44 UTC
Labels: processed
