### ISSUE TITLE
Incorrect result order for autocomplete

### ISSUE THREAD

**Issue by Joxit** [pelias/api#1279] opened 2019-04-16 13:24 UTC
I found an inconsistent result for autocomplete (I think it's since 3.58.0).

When I search [`160 avenue aristide briand bagneux`](https://pelias.github.io/compare/#/v1/autocomplete%3Ftext=160%20avenue%20aristide%20briand%20bagneux), the exact match is on second position instead of the first one.

 1) 160 Avenue Marx Dormoy, Bagneux, France
 2) 160 Avenue Aristide Briand, Bagneux, France
 3) 152/160 Avenue Aristide Briand - CS 80013, Bagneux, France
 4) 160th Avenue, Prairie Creek Township, IL, USA
 5) 160th Avenue, Rapid City East, SD, USA
 6) 160th Avenue, Winnebago, IA, USA
 7) 160th Avenue, comté de Warren, IA, USA
 8) 160th Avenue, Ringgold, IA, USA
 9) 160th Avenue, comté de Des Moines, IA, USA
10) 160th Avenue, Eliza Township, IL, 

It works well for 3.57.0

Should we re sort results before sending them ?

**Comment by orangejulius** [comment] 2019-04-17 16:12
Hey @Joxit,
This is a good test case.

I think this is more caused by `addressit`, which thinks that `avenue` _always_ comes at the _end_ of a street name. 

Here's the parser output:
```
"parsed_text": {
  "street": "160 avenue",
  "regions": [
    "aristide briand bagneux"
  ]
},
```

It's therefore trying to use `aristide briand` as part of the admin area boosts, which doesn't do anything. If you put a comma in the right place to help the address parsing out, everything works:

[/v1/autocomplete?text=160 avenue aristide briand, bagneux](https://pelias.github.io/compare/#/v1/autocomplete%3Ftext=160%20avenue%20aristide%20briand,%20bagneux)

I'd rather not go down the re-sorting path for autocomplete, but I do think it's time for revisiting what parsing logic (if any) the autocomplete endpoint uses so that we can fix this case

**Comment by Joxit** [comment] 2019-04-17 17:13
In fact, this works well in our production server ([result here](https://www.jawg.io/docs/apidocs/places/demo/?query=autocomplete?access-token=9UqBQwtm5u7uvcVTfONJ0nBOw0rqC6PiK441lMXszrgKELS5dWhR1O3rcRkUc3tn&text=160%20avenue%20aristide%20briand%20bagneux)) which is in v3.53.0.

`160 Avenue Aristide Briand, Bagneux, France` is still in first position on our server and `Marx Dormoy` in second even if `aristide briand bagneux` is in the region part with `addressit`.

:+1: for the parsing logic :smile:

**Comment by orangejulius** [comment] 2019-10-03 20:24
This is (finally) fixed as of https://github.com/pelias/api/pull/1287 and the new Pelias parser!! :tada: 

[/v1/autocomplete?text=160 avenue aristide briand bagneux](https://pelias.github.io/compare/#/v1/autocomplete%3Ftext=160%20avenue%20aristide%20briand%20bagneux)
![Screenshot_2019-10-03_16-23-03](https://user-images.githubusercontent.com/111716/66161431-409b1200-e5fa-11e9-8309-7f7ade381d0e.png)

**Closed by orangejulius** 2019-10-03 20:24 UTC
